// POST /api/proofs/backfill
//
// Re-runs rescue-prove for verified findings that either (a) have no PoE
// yet or (b) have a PoE generated by an older engine version than the
// current one. Returns a streaming-style JSON summary at the end.
//
// Body (all optional):
//   {
//     limit?: number,                  // cap on findings to process (default 50)
//     dryRun?: boolean,                // when true, just lists what WOULD run
//     onlyChainIds?: number[],         // restrict to these chains
//     forceAll?: boolean,              // re-run even for findings with current-engine PoE
//     skipExposureGate?: boolean,      // bypass the "skip $0 contracts" optimization
//   }
//
// Auth: HTTP basic auth (Next.js middleware-level), no separate token.

import { NextResponse } from "next/server";
import { rawDb } from "@/src/db/client";
import { bootOnce } from "@/src/server/boot";
import { rescueProve, ENGINE_VERSION as CURRENT_RESCUE_ENGINE_VERSION } from "@/src/server/sim/rescue-prove";
import type { PoeVerdict } from "@/src/server/sim/poe-store";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 600;

interface BackfillItem {
  id: string;
  rule_id: string;
  contract_address: string;
  chain_id: number;
  simulation_evidence_json: string | null;
  existing_engine_version: string | null;
  existing_verdict: string | null;
}

export async function POST(req: Request) {
  bootOnce();
  let body: any = {};
  try {
    body = await req.json();
  } catch {}
  const limit = clampInt(body?.limit, 1, 500, 50);
  const dryRun = !!body?.dryRun;
  const onlyChainIds: Set<number> | null = Array.isArray(body?.onlyChainIds)
    ? new Set(body.onlyChainIds.filter((n: any) => typeof n === "number"))
    : null;
  const forceAll = !!body?.forceAll;

  // Eligible candidates: verified finding, has a contract+chain, in a rule
  // family rescue-prove supports, and either has no PoE OR the latest
  // PoE is stale (engine_version < current OR the recorded engine is
  // different entirely).
  const rows = rawDb
    .prepare(
      `SELECT
         f.id, f.rule_id, f.contract_address, f.chain_id, f.simulation_evidence_json,
         (
           SELECT engine_version FROM proofs_of_exploit p
            WHERE p.finding_id = f.id ORDER BY created_at DESC LIMIT 1
         ) AS existing_engine_version,
         (
           SELECT verdict FROM proofs_of_exploit p
            WHERE p.finding_id = f.id ORDER BY created_at DESC LIMIT 1
         ) AS existing_verdict
       FROM findings f
       WHERE f.simulation_status = 'verified'
         AND f.contract_address IS NOT NULL
         AND f.chain_id IS NOT NULL
         AND (
           f.rule_id LIKE 'call.%'
           OR f.rule_id LIKE 'control.unguarded_selfdestruct%'
           OR f.rule_id LIKE 'init.%'
           OR f.rule_id LIKE 'economic.%'
         )
       ORDER BY f.discovered_at DESC`,
    )
    .all() as BackfillItem[];

  const candidates: BackfillItem[] = [];
  for (const r of rows) {
    if (onlyChainIds && !onlyChainIds.has(r.chain_id)) continue;
    if (!forceAll) {
      // Skip when there's a PoE at the current engine version and the
      // verdict is one that wouldn't change on re-run (true_positive_*
      // are sticky; verdicts that depend on env/exposure/heuristics can
      // change so we still re-run those when they're stale).
      if (
        r.existing_engine_version === CURRENT_RESCUE_ENGINE_VERSION &&
        (r.existing_verdict === "true_positive_drained" ||
          r.existing_verdict === "true_positive_partial")
      ) {
        continue;
      }
    }
    candidates.push(r);
    if (candidates.length >= limit) break;
  }

  if (dryRun) {
    return NextResponse.json({
      dryRun: true,
      currentEngineVersion: CURRENT_RESCUE_ENGINE_VERSION,
      totalEligible: rows.length,
      wouldRun: candidates.length,
      candidates: candidates.map((c) => ({
        findingId: c.id,
        ruleId: c.rule_id,
        chainId: c.chain_id,
        contractAddress: c.contract_address,
        existingEngineVersion: c.existing_engine_version,
        existingVerdict: c.existing_verdict,
      })),
    });
  }

  // Run sequentially with a soft time budget. The shared anvil pool
  // serializes per-chain forks anyway, so we don't gain much from
  // Promise.all here and it'd just race the pool.
  const results: Array<{
    findingId: string;
    contractAddress: string;
    chainId: number;
    previousEngineVersion: string | null;
    previousVerdict: string | null;
    newVerdict: PoeVerdict | "error";
    newEngineVersion: string;
    rescuedAssets: number;
    totalRescuedUsd: number | null;
    durationMs: number;
    error?: string;
  }> = [];

  const startedAll = Date.now();
  for (const c of candidates) {
    const t0 = Date.now();
    try {
      const evidence = c.simulation_evidence_json
        ? JSON.parse(c.simulation_evidence_json)
        : undefined;
      const poe = await rescueProve({
        findingId: c.id,
        chainId: c.chain_id,
        contractAddress: c.contract_address,
        ruleId: c.rule_id,
        evidence,
      });
      results.push({
        findingId: c.id,
        contractAddress: c.contract_address,
        chainId: c.chain_id,
        previousEngineVersion: c.existing_engine_version,
        previousVerdict: c.existing_verdict,
        newVerdict: poe.verdict,
        newEngineVersion: poe.engineVersion,
        rescuedAssets: poe.rescuedAssets.length,
        totalRescuedUsd: poe.totalRescuedUsd,
        durationMs: Date.now() - t0,
      });
    } catch (err: any) {
      results.push({
        findingId: c.id,
        contractAddress: c.contract_address,
        chainId: c.chain_id,
        previousEngineVersion: c.existing_engine_version,
        previousVerdict: c.existing_verdict,
        newVerdict: "error",
        newEngineVersion: CURRENT_RESCUE_ENGINE_VERSION,
        rescuedAssets: 0,
        totalRescuedUsd: null,
        durationMs: Date.now() - t0,
        error: String(err?.message ?? err).slice(0, 240),
      });
    }
  }

  const verdictCounts: Record<string, number> = {};
  for (const r of results) verdictCounts[r.newVerdict] = (verdictCounts[r.newVerdict] ?? 0) + 1;

  return NextResponse.json({
    dryRun: false,
    currentEngineVersion: CURRENT_RESCUE_ENGINE_VERSION,
    totalEligible: rows.length,
    ran: results.length,
    elapsedMs: Date.now() - startedAll,
    verdictCounts,
    results,
  });
}

function clampInt(v: any, lo: number, hi: number, dflt: number): number {
  if (typeof v !== "number" || !Number.isFinite(v)) return dflt;
  return Math.max(lo, Math.min(hi, Math.floor(v)));
}
